In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# Load the base VGG16 model
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# Data generators for training and testing
train_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)
test_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)

# Directories for training and testing data
train_dir = '/content/drive/MyDrive/10Classes/train'
test_dir = '/content/drive/MyDrive/10Classes/test'

# Create data generators
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    shuffle=True
)

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    shuffle=False
)

# Define the model architecture
model = Sequential([
    base_model,
    Flatten(),
    Dense(256, activation='relu'),
    Dense(10, activation='softmax')  # Assuming there are 10 classes
])

# Freeze the layers of the base model
base_model.trainable = False

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])

# Train the model
model.fit(train_generator, steps_per_epoch=len(train_generator), epochs=5)

# Predict on the test set
y_pred = model.predict(test_generator)
y_pred = np.argmax(y_pred, axis=1)  # Convert predictions to class indices

# Get true class indices
y_true = test_generator.classes

# Calculate and print the confusion matrix
cm = confusion_matrix(y_true, y_pred)
print('Confusion Matrix:')
print(cm)

# Generate a classification report
class_names = list(train_generator.class_indices.keys())
report = classification_report(y_true, y_pred, target_names=class_names)
print('Classification Report:')
print(report)


58889256/58889256 [==============================] - 0s 0us/step
Found 432 images belonging to 10 classes.
Found 111 images belonging to 10 classes.
Epoch 1/5
14/14 [==============================] - 280s 19s/step - loss: 47.8176 - accuracy: 0.3681
Epoch 2/5
14/14 [==============================] - 269s 19s/step - loss: 6.1696 - accuracy: 0.8032
Epoch 3/5
14/14 [==============================] - 269s 19s/step - loss: 1.2036 - accuracy: 0.9074
Epoch 4/5
14/14 [==============================] - 268s 19s/step - loss: 0.1201 - accuracy: 0.9838
Epoch 5/5
4/4 [==============================] - 71s 16s/step
Confusion Matrix:
[[ 6  0  0  0  0  0  0  5  1  0]
 [ 0 11  0  0  0  0  0  1  0  0]
 [ 3  7  2  0  0  0  0  0  0  0]
 [ 0  0  0  8  0  2  0  0  1  1]
 [ 0  0  0  0  2  2  3  2  0  0]
 [ 0  0  0  0  0  8  1  0  0  0]
 [ 0  0  0  0  1  4  6  0  0  0]
 [ 1  0  0  1  0  1  0  6  0  1]
 [ 0  0  0  0  0  3  0  1  6  2]
 [ 0  0  0  0  0  0  0  0  0 12]]
Classification Report:
                    